### ISSUE TITLE
@builder.io/cli package not found

### ISSUE THREAD

**Issue by tracy-codes** [BuilderIO/nextjs-shopify#1]
Hi!

When attempting to install the @builder.io/cli package via `npm install @builder.io/cli -g`, a 404 error occurs.

When searching on npmjs.com, there also doesn't seem to be a @builder.io/cli package on the npm registry. What's the new CLI package if this has been renamed? I can't find it anywhere in the docs.

```
➜  spacerace npm i -g @builder/cli
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@builder%2fcli - Not found
npm ERR! 404
npm ERR! 404  '@builder/cli@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tracy/.npm/_logs/2021-02-07T17_34_28_706Z-debug.log
```

![image](https://user-images.githubusercontent.com/31976538/107154409-09e0b480-6930-11eb-9fa7-a0b7e8f1952b.png)

**Comment by steve8708** [comment]
Hey @tracy-codes - thanks for reporting! Looks like the CLI was mistakenly published a private package. Should be public now, can you let us know if it works as expected for you?

**Comment by tracy-codes** [comment]
> Hey @tracy-codes - thanks for reporting! Looks like the CLI was mistakenly published a private package. Should be public now, can you let us know if it works as expected for you?

Thank you for the quick response here! It looks like that was the issue 😊. We're now cranking with testing out builder.io as our new preferred cms for client work.

**Comment by steve8708** [comment]
Fantastic @tracy-codes - look forward to it, and don't hesitate to reach out to us for anything you need (here in github, support@builder.io, or the in app chat widget too) and we're happy to help make everything goes smoothly for you!
