### ISSUE TITLE
Exposing API keys

### ISSUE THREAD

**Issue by troy-halpin** [BuilderIO/nextjs-shopify#13]
Hi! I was playing around with Builder and this example, and I noticed that your api key and other keys that should be env variables seem to be stored publicly here? I'm pretty new to shopify, but I imagine these should be in an env and not pushed. Hopefully I'm wrong and feel free to close this if I am 😄 

https://github.com/BuilderIO/nextjs-shopify/blob/d30a3de10385845943fdaa771d398089472cd58b/builder/settings.json#L13

**Comment by teleaziz** [comment]
Thanks @troy-halpin for reporting, Builder's public API keys are meant to be public and there are no concerns in exposing them. 

Feel free to add `.env` files to .gitignore once you connect your real store.

**Comment by troy-halpin** [comment]
Awesome, thanks!
