### ISSUE TITLE
Can't get Builder IO working properly

### ISSUE THREAD

**Issue by icarillo** [BuilderIO/nextjs-shopify#14]
Congrats on the product and mainly on the UI, it is really beautiful...

I've been trying Builder in the last 2 days and found some bugs, and challenges using it. I am not sure if I am doing something wrong.
I will list all my findings below because I think it is easier for me to list, and maybe easier for you to correlate the issues if possible.
As I've tried fixing the problems as I go (only using the UI) maybe one problem led to another 🤷🏼‍♂️, so I listed the steps I remember I took.

Please let me know if you think would be better to have each issue created separately next time.

**NOTE: All issues listed were found running local env. (`npm run dev`)**

### Issue

1. I can't get Builder IO working properly after connecting to my Shopify Development Store.
2. Two warnings coming from `@builder.io` modules:
```
Warning: componentWillMount has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.

Please update the following components: TabsComponent
```
```
Warning: React does not recognize the `_newProperty` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `_newproperty` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

### Expected and actual behaviors

- [x] Being able to link Builder to my store (Done easily 👍🏼 )
- [ ] Being able to preview the pages inside Builder
> I couldn't see some of the pages for example the `Product Page > Generic template` **(image is attached)** and I guess it is because of the URL `${space.siteUrl}/product/${previewProduct.handle}` not reading the variables. If I change this URL manually to an existing page and product handle, it works 👍🏼 
- [ ] Being able to edit the previewed pages
> I could **somewhat** edit the pages but I found it a little buggy:
> - Some times the Components weren't added to the view at all and I needed to refresh the page several times to get it back working
> - When I removed all the Components from the view (let's say the design team wants a "fresh" start), I couldn't add any other Components **(video is attached)**
- [x] Being able to see the changes on the site after publishing
- [x] Being able to recover the previews versions inside the `HISTORY` tab 👍🏼 

### Steps to reproduce:

1. Clone this repo
2. [Create a Dev Store on Shopify](https://help.shopify.com/en/partners/dashboard/managing-stores/development-stores)
3. Add some dummy data ( I used the app [Simple Sample Data](https://apps.shopify.com/simple-sample-data) to add some data to my store )
4. Follow the [README.md](https://github.com/BuilderIO/nextjs-shopify/blob/ef14f20642e96ccd64497c007ed77e5336cc05cd/README.md) directions until you get your store linked
5. Go to BuilderIO and try to edit `Product Page > Generic template`
6. Change the URL on the top right manually to something like `http://localhost:3000/product/vans-authentic-multi-eyelets-gradient-crimson` using a valid handle of course
7. Remove all Components in the view
8. Try to drag and drop a component to the view

### Attachments

https://user-images.githubusercontent.com/40901706/115947075-32317700-a47a-11eb-97d9-b9d0b2184b9d.mov

<img width="600" alt="Screen Shot 2021-04-23 at 8 03 56 PM" src="https://user-images.githubusercontent.com/40901706/115947112-67d66000-a47a-11eb-962d-b582d9b52541.png">
<img width="600" alt="Screen Shot 2021-04-23 at 8 04 49 PM" src="https://user-images.githubusercontent.com/40901706/115947114-69078d00-a47a-11eb-985b-72cd46ecca61.png">
<img width="600" alt="Screen Shot 2021-04-23 at 8 05 08 PM" src="https://user-images.githubusercontent.com/40901706/115947115-69078d00-a47a-11eb-858d-2860ada2dc9e.png">

**Comment by teleaziz** [comment]
Hey @icarillo thanks for the kind words, glad you're liking the platform, did a couple of updates today that should make the user experience better setting up by learning from your issues here so in the future users will have a better experience.

>I couldn't see some of the pages for example the Product Page > Generic template (image is attached) and I guess it is because of the URL ${space.siteUrl}/product/${previewProduct.handle} not reading the variables. If I change this URL manually to an existing page and product handle, it works 👍🏼

There's a preview field on the page that was not setup correctly, updated the flow to show a picker when that happen, doesn't apply retroactively, so in your case you only need to pick a preview product from the options tab 
![image](https://user-images.githubusercontent.com/5093430/116159085-7ef89600-a6a4-11eb-8599-70afaa227806.png)




>Some times the Components weren't added to the view at all and I needed to refresh the page several times to get it back working
When I removed all the Components from the view (let's say the design team wants a "fresh" start), I couldn't add any other Components (video is attached)

This was a mistake in the some of the commits dating back, I left some pixel tags that doesn't show while editing,[it's not in the code anymore](https://github.com/BuilderIO/nextjs-shopify/commit/2e82c84cc9534b1937ee2160ed75683cc2e1301c), fix doesn't apply retroactively, so you can basically delete it in the layers tab, it's under name `img`
![Screen Shot 2021-04-26 at 3 35 32 PM](https://user-images.githubusercontent.com/5093430/116159415-0cd48100-a6a5-11eb-9489-90dc12fdb7e0.png)

**Comment by teleaziz** [comment]
@icarillo just checking if you had a chance to try the suggestions above?
Closing as this all is solved for brand new spaces
