### ISSUE TITLE
Unhandled Run Time Error

### ISSUE THREAD

**Issue by mikecicutto** [BuilderIO/nextjs-shopify#16]
Hello,  I'm having issues adding my product on builder.io.  It show's all the products but immediately after adding it throws an error.
![2021-05-27 (2)](https://user-images.githubusercontent.com/70130713/120051597-de6cfd00-bfe6-11eb-9328-623094c02f81.png)

**Comment by teleaziz** [comment]
Hi @mikecicutto anything you can provide more about this error? reproduction steps and your space's`public api key` would be appreciated.

**Comment by teleaziz** [comment]
Closing this issue for now, please create a new one and add reproduction steps if you ran into this issue.
