### ISSUE TITLE
very low performance

### ISSUE THREAD

**Issue by ethanSkHung** [BuilderIO/nextjs-shopify#17]
Hi,
after I set up everything and try to use the builder to generate the website. 
it seems very slow. I need 41.9s to render the first contentful paint.
is there anything I got wrong?

![image](https://user-images.githubusercontent.com/76714680/124974853-e006f780-e05f-11eb-9f57-43a162797b9b.png)

**Comment by teleaziz** [comment]
@ethanSkHung how are you testing this? I recommend testing on a production build and deploy to vercel or netlify, many things could affect the score on localhost

**Comment by teleaziz** [comment]
closing this issue as it's unlikely an issue with a production build, please feel free to reopen if you have an online link to test this further
