### ISSUE TITLE
Add yarn support [TypeError: Cannot read properties of null (reading 'useContext')]

### ISSUE THREAD

**Issue by teknology** [BuilderIO/nextjs-shopify#34]
During a yarn run dev, I get the error 

TypeError: Cannot read properties of null (reading 'useContext')

Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'useContext')

Call Stack
useContext
node_modules/@emotion/styled/node_modules/react/cjs/react.development.js (1616:0)
eval
node_modules/@emotion/styled/base/dist/emotion-styled-base.browser.esm.js (122:39)
eval
node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js (36:0)
renderWithHooks
node_modules/react-dom/cjs/react-dom.development.js (14985:0)
updateForwardRef
node_modules/react-dom/cjs/react-dom.development.js (17044:0)
beginWork
node_modules/react-dom/cjs/react-dom.development.js (19098:0)
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js (3945:0)
Object.invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js (3994:0)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (4056:0)
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js (23964:0)
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js (22776:0)
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js (22707:0)
renderRootSync
node_modules/react-dom/cjs/react-dom.development.js (22670:0)
performSyncWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (22293:0)
eval
node_modules/react-dom/cjs/react-dom.development.js (11327:0)
unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js (468:0)
runWithPriority$1
node_modules/react-dom/cjs/react-dom.development.js (11276:0)
flushSyncCallbackQueueImpl
node_modules/react-dom/cjs/react-dom.development.js (11322:0)
flushSyncCallbackQueue
node_modules/react-dom/cjs/react-dom.development.js (11309:0)
scheduleUpdateOnFiber
node_modules/react-dom/cjs/react-dom.development.js (21893:0)
Object.enqueueSetState
node_modules/react-dom/cjs/react-dom.development.js (12467:0)
Component.setState
node_modules/@builder.io/react/node_modules/react/cjs/react.development.js (352:0)
eval
node_modules/@builder.io/react/dist/builder-react.es5.js (15:25478)
BehaviorSubject.next
node_modules/@builder.io/sdk/dist/index.esm.js (171:0)
eval
node_modules/@builder.io/sdk/dist/index.esm.js (2297:0)

**Comment by teleaziz** [comment]
Hey @teknology , all the recent issues (#33 , #32 ) you opened indicates an inaccurate packages resolution, there's no yarn.lock in this repo, please use npm to fix this error: 
```
rm -rf node_modules
npm install
npm run dev
```


I'll keep this issue open to look into adding yarn support

**Comment by teknology** [comment]
> Hey @teknology , all the recent issues (#33 , #32 ) you opened indicates an inaccurate packages resolution, there's no yarn.lock in this repo, please use npm to fix this error:
> 
> ```
> rm -rf node_modules
> npm install
> npm run dev
> ```
> 
> I'll keep this issue open to look into adding yarn support

Awesome! Thank you. I find yarn to be a lot smoother with package management hence the use.

**Comment by teknology** [comment]
A quick update. I fixed 

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parser' is not defined by "exports" in /Users/Tek/Documents/Sites/aareact/node_modules/next/node_modules/postcss/package.json

By running 

`nvm use 16
rm -rf node_modules
npm install
npm run dev
`

**Comment by zsirfs** [comment]
I also encountered this problem, how did you solve it?

**Comment by Simvolick** [comment]
For me 

```
npm run dev
```

works just fine, but when I use

```
next dev
```

it throws the same issue

**Comment by FreePhoenix888** [comment]
# Solution
Update `next` package in your package to the latest version
```
npm install next@latest
```

**Comment by steve8708** [comment]
thanks @FreePhoenix888!
