### ISSUE TITLE
Error after adding product list/collection in builder.io

### ISSUE THREAD

**Issue by wanderingcoderr** [BuilderIO/nextjs-shopify#4]
I am new to using builder.io and also to next.js, all the setup went well and I was able to build the app and get it working.
But when I tried to add product list or collection from the builder.io portal, the next.js app started giving the below error:

![image](https://user-images.githubusercontent.com/38850666/109146354-bd97d000-7789-11eb-8e10-82086d10f2fb.png)
 
I haven't deployed the app yet, its running on localhost:3000
 I am not sure if I missed any step or its some other issue.
 Any help is appreciated,
 Thanks

**Comment by teleaziz** [comment]
Thanks @wanderingcoderr for reproting, addressed it in the pr above

**Comment by wanderingcoderr** [comment]
hi @teleaziz thanks for the quick response, but I am still facing the same error.
I took the latest and run the application, still getting the same error as above

![image](https://user-images.githubusercontent.com/38850666/109202850-76c9ca80-77c9-11eb-8883-9759eb3acee2.png)

![image](https://user-images.githubusercontent.com/38850666/109202903-81845f80-77c9-11eb-8e7a-d3e408d56378.png)

**Comment by teleaziz** [comment]
Hey @wanderingcoderr, should be fixed in the latest commit, please pull from master
