### ISSUE TITLE
 Unable to install nextjs-shopify project due to dependency problems

### ISSUE THREAD

**Issue by mainlyhigh** [BuilderIO/nextjs-shopify#41]
I am trying to install the nextjs-shopify project, but I am having dependency problems. I have tried using npm to update the dependencies and using the -force flag, but the more I try the more problems I get. Is there anyone willing to help me figure out what I'm doing wrong and how I can get this working?

**Comment by teleaziz** [comment]
Hi @mainlyhigh what are the issues you're running into? 

make sure you're on node version <=16

**Comment by teleaziz** [comment]
closing this issue, all dependencies issue were resolved
