### ISSUE TITLE
CORS error with the product/[handle].tsx with plugin-shopify

### ISSUE THREAD

**Issue by jeanfrancoislarente** [BuilderIO/nextjs-shopify#44]
When trying to load a product detail page in the iFrame, the product details seem to flash quickly on the screen then it goes blank (grey). No errors on the site but the console is riddled with CORS issues.

The odd part is that it's between the origin https://builder.io and https://cdn.builder.io. It seems to be complaining about `plugin-shopify`.

The specific call is to the Shopify plugin and I've traced it to the point where it becomes code that I don't have access to.

The products on the home page are loading fine, so it doesn't seem to be an issue with the Shopify connection.

CORS error:
```
    Access to fetch at 'https://cdn.builder.io/api/v1/shopify/storefront/product/gid://shopify/Product/8132652663105?apiKey=e9da8b4ec1994cafb66f28c23b884c5c&pluginId=@builder.io/plugin-shopify' from origin 'https://builder.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Posted [on forum](https://forum.builder.io/t/cors-error-with-nextjs-shopify-sample/3289) as well but no solid leads yet and I'd really love to make progress on this!

**Comment by jeanfrancoislarente** [comment]
Hey @teleaziz 

I'm not sure how best to do that, my code is in a private repo. However, I haven't customized much of the repo however.

I'm happy to invite someone from BuilderIO to my private repository.

**Comment by teleaziz** [comment]
Latest release of the API addresses this issue, thanks for reporting
