### ISSUE TITLE
headless.builders not loading on my iphone 

### ISSUE THREAD

**Issue by erichodges** [BuilderIO/nextjs-shopify#8]
Hi,

I've tried to load the demo site on my iphone X with iOS 14.4.1 in both Safari and Brave and it will not load. Maybe some DNS issue with the .builders domain?

- Eric

**Comment by teleaziz** [comment]
H i @erichodges , thanks for reporting, I wasn't able to reproduce this, we just did a complete re-design to add theming support, please give it another shot and feel free to re-open this with reproduction instructions if you run into this again.
